jobs:
- name: deploy-kibosh
  plan:
  - aggregate:
    - get: stemcell
    - get: labs
    - get: silk-cni
    - get: scale
  - task: pre-merge-template
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: starkandwayne/concourse
      inputs:
      - name: labs
      outputs:
      - name: merged
      run:
        path: bash
        args:
        - -ec
        - |
          out=$(pwd)/merged/base.yml
          pushd labs/basel-2018/kibosh-the-ultimate-service-broker/setup
          bosh int kubo-deployment/manifests/cfcr.yml \
            -o kibosh/kubo-ops/add-lb-extension-worker.yml \
            -o kibosh/kubo-ops/add-addon-spec.yml \
            -l <(bosh int kibosh/kibosh-spec.yml  -l kibosh/vars.yml) -l kibosh/vars.yml > ${out}
  - put: deploy
    params:
      manifest: merged/base.yml
      stemcells: [ stemcell/stemcell.tgz ]
      ops_files:
      - labs/basel-2018/kibosh-the-ultimate-service-broker/setup/kubo-deployment/manifests/ops-files/use-runtime-config-bosh-dns.yml
      - labs/basel-2018/kibosh-the-ultimate-service-broker/setup/kubo-deployment/manifests/ops-files/add-hostname-to-master-certificate.yml
      - silk-cni/silk-cni.yml
      - scale/scale.yml
      vars:
        api-hostname: 35.234.73.217
        worker-hostname: 35.198.102.57
  - put: bosh-errand
    params:
      name: apply-addons

resources:
- name: labs
  type: git
  source:
    uri: https://github.com/cloudfoundry/summit-hands-on-labs
    branch: cf-deployment-submodule-fex
    submodules:
      - basel-2018/kibosh-the-ultimate-service-broker/setup/kubo-deployment

- name: stemcell
  type: bosh-io-stemcell
  source: { name: ((bosh_stemcell)) }

- name: deploy
  type: bosh-deployment
  source:
    deployment: cfcr
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))

- name: bosh-errand
  type: bosh-errand
  source:
    deployment: cfcr
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))

- name: silk-cni
  type: file
  source:
    filename: silk-cni.yml
    content:
    - type: replace
      path: /instance_groups/name=worker/jobs/-
      value:
        name: silk-cni
        release: silk
        consumes:
          cf_network: { from: cf_network, deployment: cf }
        properties:
          dns_servers:
          - 169.254.0.2
    - type: replace
      path: /instance_groups/name=worker/jobs/-
      value:
        name: vxlan-policy-agent
        release: silk
        properties:
          ca_cert: "((/((bosh_name))/cf/network_policy_ca.certificate))"
          client_cert: "((/((bosh_name))/cf/network_policy_client.certificate))"
          client_key: "((/((bosh_name))/cf/network_policy_client.private_key))"
    - type: replace
      path: /instance_groups/name=worker/jobs/-
      value:
        name: silk-daemon
        release: silk
        consumes:
          cf_network: { from: cf_network, deployment: cf }
        properties:
          ca_cert: ((/((bosh_name))/cf/silk_ca.certificate))
          client_cert: ((/((bosh_name))/cf/silk_daemon.certificate))
          client_key: ((/((bosh_name))/cf/silk_daemon.private_key))
    - type: replace
      path: /instance_groups/name=worker/jobs/name=kubelet/properties/cni-bin-dir?
      value: /var/vcap/packages/silk-cni/bin
    - type: replace
      path: /instance_groups/name=worker/jobs/name=kubelet/properties/cni-conf-dir?
      value: /var/vcap/jobs/silk-cni/config/cni
    - type: replace
      path: /instance_groups/name=worker/jobs/name=kubelet/properties/network-plugin?
      value: silk
    - type: replace
      path: /releases/-
      value:
        name: silk
        sha1: 09997e05467b96bb44cd7363bc77fa224e89075e
        stemcell:
          os: ubuntu-xenial
          version: "97.19"
        url: https://storage.googleapis.com/cf-deployment-compiled-releases/silk-2.16.0-ubuntu-xenial-97.19-20181002-231717-792781445.tgz
        version: 2.16.0

- name: scale
  type: file
  source:
    filename: scale.yml
    content:
    - type: replace
      path: /instance_groups/name=master/instances
      value: 1
    - type: replace
      path: /instance_groups/name=worker/instances
      value: 1

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest

- name: bosh-errand
  type: docker-image
  source:
    repository: cfcommunity/bosh2-errand-resource

- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
    tag: latest
